### ISSUE TITLE
NameError: uninitialized constant Sinatra::Sprockets::Manifest when precompiling assets

### ISSUE THREAD

**Issue by designcitypl** [kalasjocke/sinatra-asset-pipeline#70] opened 2018-05-22 23:47 UTC
Hi, I had the same error with precompiling assets like this one described in the issue
https://github.com/kalasjocke/sinatra-asset-pipeline/pull/62
> NameError: uninitialized constant Sinatra::Sprockets::Manifest

I found this changes https://github.com/kalasjocke/sinatra-asset-pipeline/commit/364069d1b4adc5261183b699e141ecfffe7c4460#diff-88eb5ff86459193ecce7995b8773fcb9R24 deletes `::` in `::Sprockets::Manifest`

I don't really know is it real issue, but I got one and adding this `::` again fixed it for me:
https://github.com/designcitypl/sinatra-asset-pipeline/commit/d63604251a72a3c4125ef3f3b47fade6a6f412e1

**Comment by kalasjocke** [comment] 2018-06-02 11:44
That's strange. I'm not sure why it happens for you, I would love if you could spend some more time digging into this and if you find anything submit a pull request. I can't reproduce it locally. Closing this as a wont fix since it seems to be working for most people using this gem.

**Closed by kalasjocke** 2018-06-02 11:44 UTC
